eureka:
    instance:
        client:
            serverUrl:
                defaultZone: http://localhost:8761/eureka/
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9191
spring:
    application:
        name: API-GATEWAY
    cloud:
        discovery:
            enabled: true
        gateway:
            routes:
            -   id: BALANCE-SERVICE
                predicates:
                - Path=/api/auth/**, /api/currency/**, /api/balance/**
                uri: lb://BALANCE-SERVICE
            -   id: PAYMENT-SERVICE
                predicates: Path=/api/payment/**
                uri: lb://PAYMENT-SERVICE
