version: '3.1'


services:

  db:
    image: mysql:8
    restart: always
    # volumes:
    #   - ./mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      # MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: balance-service-db
      host_cache_size: 0

  balance-service:
    depends_on:
      - db
    build: 
      context: ../balance-service
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Ddebug -Xmx128m
    restart: always
    ports:
      - 8080:8080
    
    container_name: balance-service
    
volumes:
  balance-db:
    
    